### ISSUE TITLE
Login button does nothing for me.

### ISSUE THREAD

**Issue by filviu** [RasmusKoit/abs_wear#12]
First: thanks for the app ! It's looking very promising, I'm happy it exists :)

**Describe the bug**
I installed the application from Google Play on a Samsung Galaxy Watch 4 classic 46mm lte. I filled out url, username and password but clicking login seems not to do anything. No error, spinning wheel or reaction. I can click it multiple times still no reaction. 

**Smartwatch(please complete the following information):**
 - Device: Samsung Galaxy Watch 4 classic 46mm lte
 - Android Version: 13 / wearos 4 / oneui 5
 - App version: 1.0.4

**Additional context**
My server url is http not https and uses a port number, i.e. it looks like http://abs.example.com:1234 and is only available inside my home wifi. (I made sure the watch is connected to said wifi) Maybe on of this could be the issue ?

**Comment by RasmusKoit** [comment]
Thanks for reporting this issue!

**Comment by RasmusKoit** [comment]
I have not implement error handling for login, but it seems you might be entering wrong password?

I was able to connect to the Audiobookshelf server, that I just created with an android emulator and also from my watch

![image](https://github.com/RasmusKoit/abs_wear/assets/29210664/9f047a3a-16f7-432b-ad20-abfd1bffffd0)

Please double check that the username, password and url are correct.
@filviu

**Comment by RasmusKoit** [comment]
Fixed by release [#1.0.5](https://github.com/RasmusKoit/abs_wear/releases/tag/1.0.5)

**Comment by filviu** [comment]
Thank you I will double-check.

**Comment by RasmusKoit** [comment]
@filviu update is now live on Play Store, thank you once again for the first issue!

**Comment by filviu** [comment]
Thanks !! Will test soon and update here.
